CREATE SEQUENCE seqTypSchiff START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seqAng START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seqInvSchiff START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seqLog START WITH 1 INCREMENT BY 1;